import { describe, expect, it } from 'vitest';
import { Scene, createDefaultScene } from '../src/core/scene/Scene';
import { ScenePlayer } from '../src/core/scene/ScenePlayer';
import type { AnimationMetadataV1 } from '../src/core/types';
import { parseSceneData, serializeSceneData, validateSceneData } from '../src/io/sceneMetadata';
function metadata():AnimationMetadataV1{return{version:1,spriteSheet:{image:'actor.png',rows:1,columns:3,margin:{x:0,y:0},spacing:{x:0,y:0},transparency:{mode:'nativeAlpha',color:'#000000',tolerance:0}},animations:{walk:{row:0,frames:[0,1,2],fps:10,frameDurations:{},playback:{speed:1,loopMode:'loop',loopCount:-1,randomStart:false},transform:{anchor:{x:.5,y:1},offset:{x:0,y:0},scale:{x:1,y:1},flipX:false,flipY:false},frameOffsets:{},events:[],collision:{frames:{}}}}};}
describe('Scene',()=>{it('duplicates independent instances',()=>{const s=new Scene(createDefaultScene()),a=s.addInstance('actor','walk',100,200),b=s.duplicateInstance(a.id);expect(b?.id).not.toBe(a.id);expect(b?.transform.x).toBe(124);});});
describe('ScenePlayer',()=>{it('honors start-delay boundary',()=>{const s=new Scene(createDefaultScene()),a=s.addInstance('actor','walk');a.playback.startDelay=100;const p=new ScenePlayer(s.data,new Map([['actor',metadata()]]));p.play();p.update(90);expect(p.currentFrame(a.id)).toBe(0);p.update(20);expect(p.currentFrame(a.id)).toBe(0);p.update(90);expect(p.currentFrame(a.id)).toBe(1);});it('pauses resumes and restarts',()=>{const s=new Scene(createDefaultScene()),a=s.addInstance('actor','walk'),p=new ScenePlayer(s.data,new Map([['actor',metadata()]]));p.play();p.update(100);expect(p.currentFrame(a.id)).toBe(1);p.pause();p.update(200);expect(p.currentFrame(a.id)).toBe(1);p.play();p.update(100);expect(p.currentFrame(a.id)).toBe(2);p.restart();expect(p.currentFrame(a.id)).toBe(0);});it('combines scene and instance speed',()=>{const s=new Scene(createDefaultScene()),a=s.addInstance('actor','walk');a.playback.speed=2;const p=new ScenePlayer(s.data,new Map([['actor',metadata()]]));p.setPlaybackSpeed(.5);p.play();p.update(100);expect(p.currentFrame(a.id)).toBe(1);});});
describe('scene metadata',()=>{it('round trips v1 scene',()=>{const s=new Scene(createDefaultScene());s.setBundleReference('actor',{image:'actor.png',metadata:'actor.animation.json'});s.addInstance('actor','walk');expect(validateSceneData(s.data)).toEqual([]);expect(parseSceneData(serializeSceneData(s.data))).toEqual(s.data);});});
