import type { AnimationBundle } from '../../core/bundle/AnimationBundle';
import type { CollisionBox, CollisionKind, Vec2 } from '../../core/types';
import type { SceneDataV1, SceneDebugOptions, SceneInstanceData } from '../../core/scene/SceneTypes';
import type { ScenePlayer } from '../../core/scene/ScenePlayer';

type Bounds={x:number;y:number;width:number;height:number};
export class SceneRenderer{
 private layouts=new Map<string,Bounds>(); private cache=new Map<string,HTMLCanvasElement>(); private view={scale:1,offsetX:0,offsetY:0};
 render(canvas:HTMLCanvasElement,scene:SceneDataV1,bundles:Map<string,AnimationBundle>,player:ScenePlayer,selectedId:string|null,zoom:number,debug:SceneDebugOptions):void{
  const ctx=canvas.getContext('2d'); if(!ctx)return; const{width,height}=canvas; ctx.clearRect(0,0,width,height); ctx.fillStyle='#0e141c';ctx.fillRect(0,0,width,height);
  const fit=Math.min(width/Math.max(1,scene.viewport.width),height/Math.max(1,scene.viewport.height)),scale=fit*Math.max(.1,zoom),worldW=scene.viewport.width*scale,worldH=scene.viewport.height*scale; this.view={scale,offsetX:(width-worldW)/2,offsetY:(height-worldH)/2};this.layouts.clear();
  ctx.save();ctx.translate(this.view.offsetX,this.view.offsetY);ctx.scale(scale,scale);ctx.fillStyle=scene.viewport.backgroundColor;ctx.fillRect(0,0,scene.viewport.width,scene.viewport.height);
  if(debug.showGround){ctx.save();ctx.strokeStyle='rgba(121,223,169,.72)';ctx.lineWidth=1/scale;ctx.setLineDash([10/scale,8/scale]);ctx.beginPath();ctx.moveTo(0,scene.viewport.groundY);ctx.lineTo(scene.viewport.width,scene.viewport.groundY);ctx.stroke();ctx.restore();}
  const items=scene.instances.filter(i=>i.visible).map((instance,order)=>({instance,order})).sort((a,b)=>a.instance.zIndex-b.instance.zIndex||a.order-b.order); for(const item of items)this.drawInstance(ctx,item.instance,bundles,player,selectedId,scale,debug); ctx.restore();ctx.strokeStyle='rgba(218,231,244,.26)';ctx.strokeRect(this.view.offsetX,this.view.offsetY,worldW,worldH);
 }
 hitTest(x:number,y:number,scene:SceneDataV1):string|null{for(const i of[...scene.instances].filter(i=>i.visible).sort((a,b)=>b.zIndex-a.zIndex)){const b=this.layouts.get(i.id);if(b&&x>=b.x&&x<=b.x+b.width&&y>=b.y&&y<=b.y+b.height)return i.id;}return null;}
 screenToWorld(x:number,y:number):Vec2{return{x:(x-this.view.offsetX)/this.view.scale,y:(y-this.view.offsetY)/this.view.scale};}
 clearCache():void{this.cache.clear();}
 private drawInstance(ctx:CanvasRenderingContext2D,i:SceneInstanceData,bundles:Map<string,AnimationBundle>,player:ScenePlayer,selected:string|null,viewScale:number,debug:SceneDebugOptions):void{
  const b=bundles.get(i.bundleId),clip=b?.metadata.animations[i.clip];if(!b||!clip)return;const frame=player.currentFrame(i.id)??clip.frames[0]??0;let rect;try{rect=b.spriteSheet.getFrameRect(clip.row,frame);}catch{return;}const image=this.processed(b,clip.row,frame,rect),fo=clip.frameOffsets[String(frame)]??{x:0,y:0},off={x:clip.transform.offset.x+fo.x,y:clip.transform.offset.y+fo.y};
  const ssx=i.transform.scaleX*(i.transform.flipX?-1:1),ssy=i.transform.scaleY*(i.transform.flipY?-1:1),csx=clip.transform.scale.x*(clip.transform.flipX?-1:1),csy=clip.transform.scale.y*(clip.transform.flipY?-1:1),dx=-clip.transform.anchor.x*b.spriteSheet.frameWidth,dy=-clip.transform.anchor.y*b.spriteSheet.frameHeight;
  ctx.save();ctx.translate(i.transform.x,i.transform.y);ctx.rotate(i.transform.rotation*Math.PI/180);ctx.scale(ssx,ssy);ctx.translate(off.x,off.y);ctx.scale(csx,csy);ctx.drawImage(image,dx,dy,b.spriteSheet.frameWidth,b.spriteSheet.frameHeight);const local=Math.max(Math.abs(ssx*csx),Math.abs(ssy*csy),.0001);
  if(debug.showFrameBounds||selected===i.id){ctx.strokeStyle=selected===i.id?'#ffb84d':'rgba(255,255,255,.66)';ctx.lineWidth=1.4/(viewScale*local);ctx.strokeRect(dx,dy,b.spriteSheet.frameWidth,b.spriteSheet.frameHeight);}if(debug.showCollision){ctx.save();ctx.translate(dx,dy);this.drawCollision(ctx,clip,frame,1/(viewScale*local));ctx.restore();}ctx.restore();
  if(debug.showAnchor||selected===i.id){ctx.save();ctx.strokeStyle=selected===i.id?'#ffb84d':'#ff5f73';ctx.lineWidth=1.5/viewScale;ctx.beginPath();ctx.arc(i.transform.x,i.transform.y,6/viewScale,0,Math.PI*2);ctx.moveTo(i.transform.x-10/viewScale,i.transform.y);ctx.lineTo(i.transform.x+10/viewScale,i.transform.y);ctx.moveTo(i.transform.x,i.transform.y-10/viewScale);ctx.lineTo(i.transform.x,i.transform.y+10/viewScale);ctx.stroke();ctx.restore();}
  if(debug.showInstanceName){ctx.save();ctx.fillStyle='rgba(8,13,22,.82)';ctx.font=`${12/viewScale}px system-ui`;ctx.textAlign='center';ctx.fillText(i.name,i.transform.x,i.transform.y+22/viewScale);ctx.restore();}
  this.layouts.set(i.id,this.bounds(i,b,clip,off));
 }
 private bounds(i:SceneInstanceData,b:AnimationBundle,clip:AnimationBundle['metadata']['animations'][string],off:Vec2):Bounds{const w=b.spriteSheet.frameWidth,h=b.spriteSheet.frameHeight,l=-clip.transform.anchor.x*w,t=-clip.transform.anchor.y*h,c=[{x:l,y:t},{x:l+w,y:t},{x:l+w,y:t+h},{x:l,y:t+h}].map(p=>this.toScreen(p,i,clip,off)),xs=c.map(p=>p.x),ys=c.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);return{x:minX,y:minY,width:maxX-minX,height:maxY-minY};}
 private toScreen(p:Vec2,i:SceneInstanceData,clip:AnimationBundle['metadata']['animations'][string],off:Vec2):Vec2{let x=p.x*clip.transform.scale.x*(clip.transform.flipX?-1:1)+off.x,y=p.y*clip.transform.scale.y*(clip.transform.flipY?-1:1)+off.y;x*=i.transform.scaleX*(i.transform.flipX?-1:1);y*=i.transform.scaleY*(i.transform.flipY?-1:1);const a=i.transform.rotation*Math.PI/180,rx=x*Math.cos(a)-y*Math.sin(a),ry=x*Math.sin(a)+y*Math.cos(a);return{x:this.view.offsetX+(i.transform.x+rx)*this.view.scale,y:this.view.offsetY+(i.transform.y+ry)*this.view.scale};}
 private processed(b:AnimationBundle,row:number,frame:number,r:{x:number;y:number;width:number;height:number}):HTMLCanvasElement{const t=b.metadata.spriteSheet.transparency,key=`${b.id}|${row}|${frame}|${t.mode}|${t.color}|${t.tolerance}`,cached=this.cache.get(key);if(cached)return cached;const c=document.createElement('canvas');c.width=Math.max(1,Math.round(r.width));c.height=Math.max(1,Math.round(r.height));const x=c.getContext('2d',{willReadFrequently:t.mode==='chromaKey'});if(!x)return c;x.drawImage(b.image,r.x,r.y,r.width,r.height,0,0,c.width,c.height);if(t.mode==='chromaKey'){const rgb=parseHex(t.color),d=x.getImageData(0,0,c.width,c.height),lim=Math.max(0,t.tolerance);for(let k=0;k<d.data.length;k+=4){const dr=d.data[k]-rgb.r,dg=d.data[k+1]-rgb.g,db=d.data[k+2]-rgb.b;if(Math.sqrt(dr*dr+dg*dg+db*db)<=lim)d.data[k+3]=0;}x.putImageData(d,0,0);}this.cache.set(key,c);return c;}
 private drawCollision(ctx:CanvasRenderingContext2D,clip:AnimationBundle['metadata']['animations'][string],frame:number,lw:number):void{if(clip.collision.defaultBodyBox)drawBox(ctx,clip.collision.defaultBodyBox,'body',lw);const d=clip.collision.frames[String(frame)];for(const b of d?.bodyBoxes??[])drawBox(ctx,b,'body',lw);for(const b of d?.hurtboxes??[])drawBox(ctx,b,'hurt',lw);for(const b of d?.hitboxes??[])drawBox(ctx,b,'hit',lw);}
}
function drawBox(ctx:CanvasRenderingContext2D,b:CollisionBox,k:CollisionKind,lw:number):void{const c={body:'#54b7ff',hurt:'#f1c75b',hit:'#ff6272'}[k];ctx.save();ctx.strokeStyle=c;ctx.fillStyle=`${c}22`;ctx.lineWidth=lw;ctx.fillRect(b.x,b.y,b.width,b.height);ctx.strokeRect(b.x,b.y,b.width,b.height);ctx.restore();}
function parseHex(h:string):{r:number;g:number;b:number}{const n=h.replace('#','').trim();if(!/^[0-9a-fA-F]{6}$/.test(n))return{r:0,g:0,b:0};return{r:parseInt(n.slice(0,2),16),g:parseInt(n.slice(2,4),16),b:parseInt(n.slice(4,6),16)};}
