import './styles.css';
import { AnimationPlayer } from './core/AnimationPlayer';
import { cloneClip, createDefaultClip } from './core/AnimationClip';
import { SpriteSheet } from './core/SpriteSheet';
import type { AnimationClipData, AnimationMetadataV1, CollisionBox, CollisionKind, SpriteProjectV1 } from './core/types';
import { createProcessedFrame, previewPointToFrame, renderPreview, renderSheetView, type DebugFlags, type PreviewLayout } from './editor/Renderer';
import { createDefaultMetadata, normalizedMetadata, parseMetadata, parseProject, validateMetadata } from './io/metadata';

const app = document.querySelector<HTMLDivElement>('#app');
if (!app) throw new Error('Missing #app');

app.innerHTML = `
<header class="topbar"><div class="brand"><div class="brand-mark">SF</div><div><strong>SpriteForge</strong><span>2D animation studio</span></div></div><div class="top-actions">
<label class="button primary">Load Sprite<input id="imageInput" type="file" accept="image/png,image/webp,image/jpeg" hidden></label>
<label class="button">Import Metadata<input id="metadataInput" type="file" accept="application/json,.json" hidden></label>
<label class="button">Import Project<input id="projectInput" type="file" accept="application/json,.json" hidden></label>
<button id="exportMetadata">Export Metadata</button><button id="exportProject">Export Project</button></div></header>
<main class="workspace">
<section class="panel sheet-panel"><div class="panel-title"><span>Sprite Sheet</span><span id="imageInfo" class="muted">No image loaded</span></div><div id="dropZone" class="canvas-shell drop-zone"><canvas id="sheetCanvas" width="980" height="660"></canvas><div class="drop-hint">Drop PNG / WebP here</div></div></section>
<section class="panel preview-panel"><div class="panel-title"><span>Animation Preview</span><span id="frameReadout" class="muted">Frame —</span></div><div class="canvas-shell"><canvas id="previewCanvas" width="760" height="660"></canvas></div><div class="transport"><button id="prevFrame">◀|</button><button id="playPause" class="primary">▶ Play</button><button id="stopPlayback">■ Stop</button><button id="nextFrame">|▶</button><label>Zoom <input id="previewZoom" type="range" min="0.25" max="3" step="0.05" value="1"></label><span id="zoomReadout">1.00×</span></div></section>
<aside class="inspector">
<section class="panel compact"><div class="panel-title"><span>Animations</span><button id="addClip" class="small primary">+ Add</button></div><div id="clipList" class="clip-list"></div><div class="row-actions"><button id="duplicateClip" class="small">Duplicate</button><button id="deleteClip" class="small danger">Delete</button></div></section>
<details class="panel compact" open><summary>Sprite Sheet Config</summary><div class="form-grid two"><label>Rows<input id="rows" type="number" min="1" value="4"></label><label>Columns<input id="columns" type="number" min="1" value="8"></label><label>Margin X<input id="marginX" type="number" min="0" value="0"></label><label>Margin Y<input id="marginY" type="number" min="0" value="0"></label><label>Spacing X<input id="spacingX" type="number" min="0" value="0"></label><label>Spacing Y<input id="spacingY" type="number" min="0" value="0"></label></div><div class="form-grid"><label>Transparency<select id="transparencyMode"><option value="nativeAlpha">Native alpha</option><option value="chromaKey">Chroma key</option><option value="none">None</option></select></label><div class="form-grid two tight"><label>Key Color<input id="keyColor" type="color" value="#000000"></label><label>Tolerance<input id="tolerance" type="number" min="0" max="441" value="10"></label></div></div></details>
<details class="panel compact" open><summary>Clip</summary><div id="clipEmpty" class="empty-note">Create an animation clip to edit playback.</div><div id="clipControls"><div class="form-grid"><label>Name<input id="clipName" type="text"></label><div class="form-grid two tight"><label>Row<input id="clipRow" type="number" min="0"></label><label>FPS<input id="fps" type="number" min="0.1" step="0.1"></label></div><label>Frame sequence<input id="frameSequence" type="text" placeholder="0,1,2,3,2,1"></label><div class="range-maker"><label>Start<input id="rangeStart" type="number" min="0" value="0"></label><label>End<input id="rangeEnd" type="number" min="0" value="7"></label><button id="applyRange" class="small">Apply range</button></div><div class="form-grid two tight"><label>Loop mode<select id="loopMode"><option value="loop">Loop</option><option value="once">Once</option><option value="pingPong">Ping-pong</option></select></label><label>Loop count<input id="loopCount" type="number" min="-1"></label></div><div class="form-grid two tight"><label>Speed<input id="speed" type="number" min="0.01" step="0.05"></label><label class="checkbox"><input id="randomStart" type="checkbox"> Random start</label></div><label>Current frame duration (ms)<input id="frameDuration" type="number" min="1" placeholder="Uses FPS when empty"></label></div></div></details>
<details class="panel compact" open><summary>Transform & Stabilization</summary><div class="form-grid two"><label>Anchor X<input id="anchorX" type="number" step="0.01"></label><label>Anchor Y<input id="anchorY" type="number" step="0.01"></label><label>Offset X<input id="offsetX" type="number"></label><label>Offset Y<input id="offsetY" type="number"></label><label>Scale X<input id="scaleX" type="number" step="0.05"></label><label>Scale Y<input id="scaleY" type="number" step="0.05"></label><label>Frame Offset X<input id="frameOffsetX" type="number"></label><label>Frame Offset Y<input id="frameOffsetY" type="number"></label></div><div class="inline-checks"><label><input id="flipX" type="checkbox"> Flip X</label><label><input id="flipY" type="checkbox"> Flip Y</label></div></details>
<details class="panel compact" open><summary>Frame Events</summary><div class="event-add"><input id="eventName" type="text" placeholder="deal_damage"><textarea id="eventPayload" rows="2" placeholder='Optional JSON payload, e.g. {"damage":20}'></textarea><button id="addEvent" class="small primary">Add event on current frame</button></div><div id="eventList" class="data-list"></div></details>
<details class="panel compact" open><summary>Collision</summary><div class="form-grid"><label>Box type<select id="collisionKind"><option value="body">Body</option><option value="hurt">Hurtbox</option><option value="hit">Hitbox</option></select></label><label class="checkbox"><input id="collisionEdit" type="checkbox"> Draw boxes on preview</label><button id="clearCollision" class="small danger">Clear current frame boxes</button></div><div id="collisionSummary" class="data-list"></div></details>
<details class="panel compact" open><summary>Debug View</summary><div class="inline-checks wrap"><label><input id="showGrid" type="checkbox" checked> Grid</label><label><input id="showAnchor" type="checkbox" checked> Anchor</label><label><input id="showGround" type="checkbox" checked> Ground</label><label><input id="showFrameBounds" type="checkbox" checked> Frame bounds</label><label><input id="showCollision" type="checkbox" checked> Collision</label></div></details>
<section class="panel compact"><div class="panel-title"><span>Validation</span><button id="validateNow" class="small">Check</button></div><div id="validationOutput" class="validation-output ok">Ready</div></section>
</aside>
<section class="panel timeline-panel"><div class="panel-title"><span>Timeline</span><div class="timeline-tools"><input id="appendFrameValue" type="number" min="0" value="0"><button id="appendFrame" class="small">+ Frame</button></div></div><div id="timeline" class="timeline"></div></section>
</main>`;

const q = <T extends Element>(selector: string): T => { const el = document.querySelector<T>(selector); if (!el) throw new Error(`Missing ${selector}`); return el; };
const sheetCanvas=q<HTMLCanvasElement>('#sheetCanvas'), previewCanvas=q<HTMLCanvasElement>('#previewCanvas'), imageInput=q<HTMLInputElement>('#imageInput'), metadataInput=q<HTMLInputElement>('#metadataInput'), projectInput=q<HTMLInputElement>('#projectInput'), dropZone=q<HTMLDivElement>('#dropZone');
let metadata:AnimationMetadataV1=createDefaultMetadata(), image:HTMLImageElement|null=null, imageUrl:string|null=null, selectedClipName:string|null=null, player:AnimationPlayer|null=null, playerClipRef:AnimationClipData|null=null, lastTimestamp=performance.now(), previewLayout:PreviewLayout|null=null, processedCache=new Map<string,HTMLCanvasElement>(), collisionDragStart:{x:number;y:number}|null=null, collisionDraft:{kind:CollisionKind;box:CollisionBox}|null=null;
const editor=loadEditor();
const currentClip=()=>selectedClipName?metadata.animations[selectedClipName]??null:null;
const currentFrame=()=>player?.currentFrame??currentClip()?.frames[0]??0;
const spriteSheet=()=>image?new SpriteSheet(image.naturalWidth,image.naturalHeight,metadata.spriteSheet):null;
function ensurePlayer(reset=false){const clip=currentClip();if(!clip){player=null;playerClipRef=null;return;}if(!player||playerClipRef!==clip){player=new AnimationPlayer(clip);playerClipRef=clip;player.onEvent(e=>status(`Event: ${e.name} @ frame ${e.frame}`));}else{const i=player.currentSequenceIndex;player.setClip(clip,reset);if(!reset)player.seek(Math.min(i,Math.max(0,clip.frames.length-1)));}}
function sync(reset=false){ensurePlayer(reset);syncGlobal();syncClipList();syncClip();renderTimeline();renderEvents();renderCollision();renderAll();saveEditor();}
function setVal(s:string,v:string|number){const e=q<HTMLInputElement|HTMLSelectElement>(s);if(document.activeElement!==e)e.value=String(v);} function check(s:string,v:boolean){q<HTMLInputElement>(s).checked=v;} function num(s:string,f=0){const n=Number(q<HTMLInputElement>(s).value);return Number.isFinite(n)?n:f;} function int(s:string,f=0){return Math.trunc(num(s,f));} function clamp(v:number,a:number,b:number){return Math.min(b,Math.max(a,v));}
function syncGlobal(){const s=metadata.spriteSheet;setVal('#rows',s.rows);setVal('#columns',s.columns);setVal('#marginX',s.margin.x);setVal('#marginY',s.margin.y);setVal('#spacingX',s.spacing.x);setVal('#spacingY',s.spacing.y);setVal('#transparencyMode',s.transparency.mode);setVal('#keyColor',s.transparency.color);setVal('#tolerance',s.transparency.tolerance);setVal('#previewZoom',editor.previewZoom);q<HTMLElement>('#zoomReadout').textContent=`${editor.previewZoom.toFixed(2)}×`;check('#showGrid',editor.showGrid);check('#showAnchor',editor.showAnchor);check('#showGround',editor.showGround);check('#showFrameBounds',editor.showFrameBounds);check('#showCollision',editor.showCollision);q<HTMLElement>('#imageInfo').textContent=image?`${image.naturalWidth} × ${image.naturalHeight} • ${s.image}`:s.image||'No image loaded';}
function syncClipList(){const list=q<HTMLDivElement>('#clipList');list.innerHTML='';const names=Object.keys(metadata.animations);if(!names.length){list.innerHTML='<div class="empty-note">No clips yet.</div>';return;}for(const name of names){const b=document.createElement('button');b.className=`clip-item${name===selectedClipName?' active':''}`;b.textContent=name;b.onclick=()=>{selectedClipName=name;sync(true);};list.append(b);}}
function syncClip(){const c=currentClip();q<HTMLElement>('#clipEmpty').classList.toggle('hidden',!!c);q<HTMLElement>('#clipControls').classList.toggle('hidden',!c);q<HTMLButtonElement>('#duplicateClip').disabled=!c;q<HTMLButtonElement>('#deleteClip').disabled=!c;if(!c)return;setVal('#clipName',selectedClipName??'');setVal('#clipRow',c.row);setVal('#fps',c.fps);setVal('#frameSequence',c.frames.join(','));setVal('#rangeEnd',Math.max(0,metadata.spriteSheet.columns-1));setVal('#loopMode',c.playback.loopMode);setVal('#loopCount',c.playback.loopCount);setVal('#speed',c.playback.speed);check('#randomStart',c.playback.randomStart);setVal('#anchorX',c.transform.anchor.x);setVal('#anchorY',c.transform.anchor.y);setVal('#offsetX',c.transform.offset.x);setVal('#offsetY',c.transform.offset.y);setVal('#scaleX',c.transform.scale.x);setVal('#scaleY',c.transform.scale.y);check('#flipX',c.transform.flipX);check('#flipY',c.transform.flipY);syncFrameInputs();}
function syncFrameInputs(){const c=currentClip();if(!c)return;const f=currentFrame(),o=c.frameOffsets[String(f)]??{x:0,y:0};setVal('#frameDuration',c.frameDurations[String(f)]??'');setVal('#frameOffsetX',o.x);setVal('#frameOffsetY',o.y);}
function renderAll(){const sheet=spriteSheet(),c=currentClip(),f=currentFrame();renderSheetView(sheetCanvas,image,sheet,c?.row??0,f,editor.showGrid);let processed:HTMLCanvasElement|null=null;if(image&&sheet&&c&&f>=0&&f<metadata.spriteSheet.columns){try{const r=sheet.getFrameRect(c.row,f),t=metadata.spriteSheet.transparency,key=[c.row,f,r.x,r.y,r.width,r.height,t.mode,t.color,t.tolerance].join('|');processed=processedCache.get(key)??createProcessedFrame(image,r,t.mode,t.color,t.tolerance);processedCache.set(key,processed);}catch{processed=null;}}const debug:DebugFlags={showGrid:editor.showGrid,showAnchor:editor.showAnchor,showGround:editor.showGround,showFrameBounds:editor.showFrameBounds,showCollision:editor.showCollision};previewLayout=renderPreview(previewCanvas,image,processed,sheet,c,f,editor.previewZoom,debug,collisionDraft);q<HTMLElement>('#frameReadout').textContent=c?`Frame ${f} • ${(player?.currentSequenceIndex??0)+1}/${c.frames.length}`:'Frame —';q<HTMLButtonElement>('#playPause').textContent=player?.isPlaying?'⏸ Pause':'▶ Play';}
function renderTimeline(){const el=q<HTMLDivElement>('#timeline');el.innerHTML='';const c=currentClip();if(!c){el.innerHTML='<div class="empty-note">Create a clip to build a timeline.</div>';return;}c.frames.forEach((f,i)=>{const d=document.createElement('div');d.className=`timeline-frame${i===(player?.currentSequenceIndex??0)?' current':''}`;d.draggable=true;d.dataset.index=String(i);const ec=c.events.filter(e=>e.frame===f).length,fc=c.collision.frames[String(f)],bc=(fc?.hitboxes?.length??0)+(fc?.hurtboxes?.length??0)+(fc?.bodyBoxes?.length??0),dur=c.frameDurations[String(f)];d.innerHTML=`<button class="frame-main"><span class="frame-index">${f}</span><span class="frame-meta">${dur?`${dur}ms`:''}</span><span class="markers">${ec?`<i class="event-marker">E${ec}</i>`:''}${bc?`<i class="collision-marker">B${bc}</i>`:''}</span></button><button class="frame-remove">×</button>`;d.querySelector<HTMLButtonElement>('.frame-main')!.onclick=()=>{player?.seek(i);syncFrameInputs();renderTimeline();renderEvents();renderCollision();renderAll();};d.querySelector<HTMLButtonElement>('.frame-remove')!.onclick=e=>{e.stopPropagation();if(c.frames.length<=1)return status('A clip needs at least one frame.',true);c.frames.splice(i,1);setVal('#frameSequence',c.frames.join(','));ensurePlayer();renderTimeline();renderAll();};d.ondragstart=e=>e.dataTransfer?.setData('text/plain',String(i));d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();const from=Number(e.dataTransfer?.getData('text/plain'));if(!Number.isInteger(from)||from===i)return;const [m]=c.frames.splice(from,1);c.frames.splice(i,0,m);setVal('#frameSequence',c.frames.join(','));ensurePlayer();renderTimeline();renderAll();};el.append(d);});}
function renderEvents(){const el=q<HTMLDivElement>('#eventList'),c=currentClip();el.innerHTML='';if(!c||!c.events.length){el.innerHTML='<div class="empty-note">No frame events.</div>';return;}c.events.map((event,index)=>({event,index})).sort((a,b)=>a.event.frame-b.event.frame).forEach(({event,index})=>{const row=document.createElement('div');row.className='data-row';row.innerHTML=`<span><b>F${event.frame}</b> ${escapeHtml(event.name)}</span><button class="tiny danger">×</button>`;row.querySelector('button')!.onclick=()=>{c.events.splice(index,1);renderEvents();renderTimeline();};el.append(row);});}
function renderCollision(){const el=q<HTMLDivElement>('#collisionSummary'),c=currentClip();if(!c){el.innerHTML='<div class="empty-note">No clip selected.</div>';return;}const d=c.collision.frames[String(currentFrame())],body=(c.collision.defaultBodyBox?1:0)+(d?.bodyBoxes?.length??0),hurt=d?.hurtboxes?.length??0,hit=d?.hitboxes?.length??0;el.innerHTML=`<div class="collision-counts"><span>Body ${body}</span><span>Hurt ${hurt}</span><span>Hit ${hit}</span></div><small>Drag on preview while Draw Boxes is enabled.</small>`;}
async function loadImage(file:File){if(imageUrl)URL.revokeObjectURL(imageUrl);imageUrl=URL.createObjectURL(file);const img=new Image();await new Promise<void>((res,rej)=>{img.onload=()=>res();img.onerror=()=>rej(new Error('Could not decode image'));img.src=imageUrl!;});image=img;metadata.spriteSheet.image=file.name;processedCache.clear();if(!Object.keys(metadata.animations).length)addClip();sync(true);status(`Loaded ${file.name} (${img.naturalWidth}×${img.naturalHeight}).`);}
function unique(base:string){if(!metadata.animations[base])return base;let i=2;while(metadata.animations[`${base}_${i}`])i++;return `${base}_${i}`;} function addClip(){const n=unique('animation');metadata.animations[n]=createDefaultClip(0,metadata.spriteSheet.columns);selectedClipName=n;ensurePlayer(true);}
function rename(next:string){const old=selectedClipName;if(!old||!metadata.animations[old])return;const n=next.trim();if(!n||n===old)return;if(metadata.animations[n]){status(`Animation '${n}' already exists.`,true);setVal('#clipName',old);return;}const rebuilt:Record<string,AnimationClipData>={};for(const [k,v] of Object.entries(metadata.animations))rebuilt[k===old?n:k]=v;metadata.animations=rebuilt;selectedClipName=n;sync();}
function updateSheet(){const s=metadata.spriteSheet;s.rows=Math.max(1,int('#rows',1));s.columns=Math.max(1,int('#columns',1));s.margin.x=Math.max(0,num('#marginX'));s.margin.y=Math.max(0,num('#marginY'));s.spacing.x=Math.max(0,num('#spacingX'));s.spacing.y=Math.max(0,num('#spacingY'));s.transparency.mode=q<HTMLSelectElement>('#transparencyMode').value as any;s.transparency.color=q<HTMLInputElement>('#keyColor').value;s.transparency.tolerance=Math.max(0,num('#tolerance',10));processedCache.clear();for(const c of Object.values(metadata.animations))c.row=Math.min(c.row,s.rows-1);sync();}
function parseFrames(v:string){return v.split(/[\s,]+/).filter(Boolean).map(Number).filter(n=>Number.isInteger(n)&&n>=0&&n<metadata.spriteSheet.columns);}
function updateClip(){const c=currentClip();if(!c)return;c.row=clamp(int('#clipRow'),0,metadata.spriteSheet.rows-1);c.fps=Math.max(.01,num('#fps',8));const frames=parseFrames(q<HTMLInputElement>('#frameSequence').value);if(frames.length)c.frames=frames;c.playback.loopMode=q<HTMLSelectElement>('#loopMode').value as any;c.playback.loopCount=Math.max(-1,int('#loopCount',-1));c.playback.speed=Math.max(.01,num('#speed',1));c.playback.randomStart=q<HTMLInputElement>('#randomStart').checked;c.transform.anchor={x:num('#anchorX',.5),y:num('#anchorY',1)};c.transform.offset={x:num('#offsetX'),y:num('#offsetY')};c.transform.scale={x:Math.max(.001,num('#scaleX',1)),y:Math.max(.001,num('#scaleY',1))};c.transform.flipX=q<HTMLInputElement>('#flipX').checked;c.transform.flipY=q<HTMLInputElement>('#flipY').checked;ensurePlayer();renderTimeline();renderAll();}
function updateFrame(){const c=currentClip();if(!c)return;const f=String(currentFrame()),raw=q<HTMLInputElement>('#frameDuration').value.trim();if(raw)c.frameDurations[f]=Math.max(1,Number(raw));else delete c.frameDurations[f];const o={x:num('#frameOffsetX'),y:num('#frameOffsetY')};if(!o.x&&!o.y)delete c.frameOffsets[f];else c.frameOffsets[f]=o;renderTimeline();renderAll();}
function addBox(kind:CollisionKind,box:CollisionBox){const c=currentClip();if(!c||box.width<1||box.height<1)return;const b={x:Math.max(0,box.x),y:Math.max(0,box.y),width:Math.max(0,box.width),height:Math.max(0,box.height)};if(kind==='body')c.collision.defaultBodyBox=b;else{const f=(c.collision.frames[String(currentFrame())]??={}),arr=kind==='hurt'?(f.hurtboxes??=[]):(f.hitboxes??=[]);arr.push(b);}renderCollision();renderTimeline();renderAll();}
function clearBoxes(){const c=currentClip();if(!c)return;const kind=q<HTMLSelectElement>('#collisionKind').value as CollisionKind;if(kind==='body')delete c.collision.defaultBodyBox;else{const f=c.collision.frames[String(currentFrame())];if(f){if(kind==='hurt')f.hurtboxes=[];else f.hitboxes=[];}}renderCollision();renderTimeline();renderAll();}
function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);} function base(){return(metadata.spriteSheet.image||'sprite').replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]+/g,'_');}
function exportMeta(){const errors=validateMetadata(metadata);if(errors.length){showValidation(errors);return status('Fix validation errors before export.',true);}download(`${base()}.animation.json`,normalizedMetadata(metadata,image?.naturalWidth,image?.naturalHeight));}
function exportProject(){const p:SpriteProjectV1={projectVersion:1,metadata:normalizedMetadata(metadata,image?.naturalWidth,image?.naturalHeight),editor:{...editor,selectedClip:selectedClipName}};download(`${base()}.sprite-project.json`,p);}
async function importMeta(file:File){try{metadata=parseMetadata(await file.text());selectedClipName=Object.keys(metadata.animations)[0]??null;processedCache.clear();sync(true);status('Metadata imported. Relink sprite image if needed.');}catch(e){status(e instanceof Error?e.message:'Invalid metadata',true);}}
async function importProject(file:File){try{const p=parseProject(await file.text());metadata=p.metadata;Object.assign(editor,p.editor);selectedClipName=p.editor.selectedClip&&metadata.animations[p.editor.selectedClip]?p.editor.selectedClip:Object.keys(metadata.animations)[0]??null;processedCache.clear();sync(true);status('Project imported. Relink sprite image if needed.');}catch(e){status(e instanceof Error?e.message:'Invalid project',true);}}
function showValidation(errors=validateMetadata(metadata)){const el=q<HTMLDivElement>('#validationOutput');if(!errors.length){el.className='validation-output ok';el.textContent='✓ Metadata is valid.';}else{el.className='validation-output error';el.innerHTML=`<strong>${errors.length} issue(s)</strong><ul>${errors.map(e=>`<li>${escapeHtml(e)}</li>`).join('')}</ul>`;}} function status(msg:string,error=false){const el=q<HTMLDivElement>('#validationOutput');el.className=`validation-output ${error?'error':'ok'}`;el.textContent=msg;} function escapeHtml(v:string){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));}
function loadEditor():SpriteProjectV1['editor']{const d={selectedClip:null,previewZoom:1,showGrid:true,showAnchor:true,showGround:true,showFrameBounds:true,showCollision:true};try{return{...d,...JSON.parse(localStorage.getItem('spriteforge.editor.v1')||'{}')}}catch{return d;}} function saveEditor(){localStorage.setItem('spriteforge.editor.v1',JSON.stringify({...editor,selectedClip:selectedClipName}));}

imageInput.onchange=()=>{const f=imageInput.files?.[0];if(f)void loadImage(f);imageInput.value='';}; metadataInput.onchange=()=>{const f=metadataInput.files?.[0];if(f)void importMeta(f);metadataInput.value='';}; projectInput.onchange=()=>{const f=projectInput.files?.[0];if(f)void importProject(f);projectInput.value='';};
for(const n of ['dragenter','dragover'])dropZone.addEventListener(n,e=>{e.preventDefault();dropZone.classList.add('dragging');});for(const n of ['dragleave','drop'])dropZone.addEventListener(n,e=>{e.preventDefault();dropZone.classList.remove('dragging');});dropZone.addEventListener('drop',e=>{const f=e.dataTransfer?.files?.[0];if(f?.type.startsWith('image/'))void loadImage(f);});
for(const s of ['#rows','#columns','#marginX','#marginY','#spacingX','#spacingY','#transparencyMode','#keyColor','#tolerance'])q<HTMLInputElement|HTMLSelectElement>(s).addEventListener('input',updateSheet);
q<HTMLButtonElement>('#addClip').onclick=()=>{addClip();sync(true);};q<HTMLButtonElement>('#duplicateClip').onclick=()=>{const c=currentClip();if(!c||!selectedClipName)return;const n=unique(`${selectedClipName}_copy`);metadata.animations[n]=cloneClip(c);selectedClipName=n;sync(true);};q<HTMLButtonElement>('#deleteClip').onclick=()=>{if(!selectedClipName)return;delete metadata.animations[selectedClipName];selectedClipName=Object.keys(metadata.animations)[0]??null;sync(true);};q<HTMLInputElement>('#clipName').onchange=e=>rename((e.target as HTMLInputElement).value);
for(const s of ['#clipRow','#fps','#frameSequence','#loopMode','#loopCount','#speed','#randomStart','#anchorX','#anchorY','#offsetX','#offsetY','#scaleX','#scaleY','#flipX','#flipY'])q<HTMLInputElement|HTMLSelectElement>(s).addEventListener('input',updateClip);
q<HTMLButtonElement>('#applyRange').onclick=()=>{const c=currentClip();if(!c)return;const a=clamp(int('#rangeStart'),0,metadata.spriteSheet.columns-1),b=clamp(int('#rangeEnd'),0,metadata.spriteSheet.columns-1),step=a<=b?1:-1,frames:number[]=[];for(let f=a;step>0?f<=b:f>=b;f+=step)frames.push(f);c.frames=frames;setVal('#frameSequence',frames.join(','));ensurePlayer(true);renderTimeline();renderAll();};for(const s of ['#frameDuration','#frameOffsetX','#frameOffsetY'])q<HTMLInputElement>(s).addEventListener('input',updateFrame);
q<HTMLButtonElement>('#playPause').onclick=()=>{if(!player)return;player.isPlaying?player.pause():player.play(false);renderAll();};q<HTMLButtonElement>('#stopPlayback').onclick=()=>{player?.stop();syncFrameInputs();renderTimeline();renderAll();};q<HTMLButtonElement>('#prevFrame').onclick=()=>{player?.pause();player?.stepBackward();syncFrameInputs();renderTimeline();renderEvents();renderCollision();renderAll();};q<HTMLButtonElement>('#nextFrame').onclick=()=>{player?.pause();player?.stepForward();syncFrameInputs();renderTimeline();renderEvents();renderCollision();renderAll();};q<HTMLInputElement>('#previewZoom').oninput=e=>{editor.previewZoom=Number((e.target as HTMLInputElement).value);q<HTMLElement>('#zoomReadout').textContent=`${editor.previewZoom.toFixed(2)}×`;saveEditor();renderAll();};
q<HTMLButtonElement>('#appendFrame').onclick=()=>{const c=currentClip();if(!c)return;const f=int('#appendFrameValue');if(f<0||f>=metadata.spriteSheet.columns)return status('Frame is outside configured columns.',true);c.frames.push(f);setVal('#frameSequence',c.frames.join(','));ensurePlayer();renderTimeline();};
q<HTMLButtonElement>('#addEvent').onclick=()=>{const c=currentClip();if(!c)return;const n=q<HTMLInputElement>('#eventName'),p=q<HTMLTextAreaElement>('#eventPayload'),name=n.value.trim();if(!name)return status('Event name is required.',true);let payload:unknown=undefined;if(p.value.trim())try{payload=JSON.parse(p.value);}catch{return status('Event payload must be valid JSON.',true);}c.events.push({frame:currentFrame(),name,...(payload===undefined?{}:{payload})});n.value='';p.value='';renderEvents();renderTimeline();};
function canvasPoint(e:PointerEvent){const r=previewCanvas.getBoundingClientRect();return{x:(e.clientX-r.left)*previewCanvas.width/r.width,y:(e.clientY-r.top)*previewCanvas.height/r.height};}
previewCanvas.onpointerdown=e=>{if(!q<HTMLInputElement>('#collisionEdit').checked||!previewLayout||!currentClip())return;collisionDragStart=previewPointToFrame(canvasPoint(e),previewLayout);previewCanvas.setPointerCapture(e.pointerId);};previewCanvas.onpointermove=e=>{if(!collisionDragStart||!previewLayout)return;const p=previewPointToFrame(canvasPoint(e),previewLayout),x=Math.min(collisionDragStart.x,p.x),y=Math.min(collisionDragStart.y,p.y);collisionDraft={kind:q<HTMLSelectElement>('#collisionKind').value as CollisionKind,box:{x,y,width:Math.abs(p.x-collisionDragStart.x),height:Math.abs(p.y-collisionDragStart.y)}};renderAll();};previewCanvas.onpointerup=e=>{if(!collisionDragStart||!collisionDraft)return;previewCanvas.releasePointerCapture(e.pointerId);addBox(collisionDraft.kind,collisionDraft.box);collisionDragStart=null;collisionDraft=null;renderAll();};q<HTMLButtonElement>('#clearCollision').onclick=clearBoxes;
for(const [s,k] of [['#showGrid','showGrid'],['#showAnchor','showAnchor'],['#showGround','showGround'],['#showFrameBounds','showFrameBounds'],['#showCollision','showCollision']] as const)q<HTMLInputElement>(s).onchange=e=>{editor[k]=(e.target as HTMLInputElement).checked;saveEditor();renderAll();};q<HTMLButtonElement>('#exportMetadata').onclick=exportMeta;q<HTMLButtonElement>('#exportProject').onclick=exportProject;q<HTMLButtonElement>('#validateNow').onclick=()=>showValidation();
function loop(t:number){const delta=t-lastTimestamp;lastTimestamp=t;if(player?.isPlaying){const before=player.currentSequenceIndex;player.update(delta);if(before!==player.currentSequenceIndex){syncFrameInputs();renderTimeline();renderEvents();renderCollision();}renderAll();}requestAnimationFrame(loop);} sync(true);requestAnimationFrame(loop);
